# Generated by Django 5.2.4 on 2025-07-19 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 19, 14, 14, 3, 518213, tzinfo=datetime.timezone.utc)),
        ),
    ]
