# Generated by Django 5.2.4 on 2025-07-19 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 19, 14, 53, 57, 636564, tzinfo=datetime.timezone.utc)),
        ),
    ]
